# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dl_user_dev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false