spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.30.12:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

  flyway:
    # 是否开启
    enabled: true
    # initialize the schema history table。有历史数据时，设为true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # ！！！使clean命令失效 (如果执行的脚本是执行的脚本是 V1__xxx.sql，clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉)
    clean-disabled: true
    table: order_flyway_schema_history