server:
  port: 20001
spring:
  application:
    name: import
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Zhen910831
    url: jdbc:mysql://rm-uf6ut59j6ne4bi9tgho.mysql.rds.aliyuncs.com:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

# 自动重启设置
  devtools:
    restart:
      # 自定义这些排除项
      exclude: static/**,public/**
      # 禁用重新启动（这仍将初始化重新启动类加载器，但不会监视文件更改）
#      enabled: true
      # 配置其他需要监视更改的路径
#      additional-paths:

## mybaits 模块配置
mybatis-plus:
  typeAliasesPackage: com.coderandyli.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    # 逻辑删除字段
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logging:
  level:
    com.coderandyli: debug
