---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lizhen.
--- DateTime: 2019-07-10 15:35
--- 获取集合中所有元素
---

local key=KEYS[1]

local list=redis.call("lrange",key,0,-1);

return list;