---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lizhen.
--- DateTime: 2019-07-15 11:58
---
---
local lockKey = KEYS[1]
local lockValue = KEYS[2]

-- get key
local result_1 = redis.call('get', lockKey)
if result_1 == lockValue
then
    local result_2 = redis.call('del', lockKey)
    return result_2
else
    return false
end