server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test_db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: root
#    password: LiZHen123
#    url: jdbc:mysql://rm-uf6ut59j6ne4bi9tgho.mysql.rds.aliyuncs.com/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  application:
    name: project-demo
#  redis:
#    sentinel:
#      master: mymaster
#      nodes: 39.104.124.39:26379

#    host: 39.104.124.39
#    port: 6379
#    database: 1

#    lettuce:
#      pool:
#        max-active: 10


#mybaits-plus config
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    # 逻辑删除字段
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    #打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.coderandyli: debug