server:
  port: 8081
spring:
  application:
    name: redis-demo
  redis:
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 1
  mvc:
    async:
      request-timeout:

logging:
  level:
    com.coderandyli: debug




